# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

default:
	gcc -Wall -Wextra -lz -o lab1b-server lab1b-server.c
	gcc -Wall -Wextra -lz -o lab1b-client lab1b-client.c

server:
	gcc -Wall -Wextra -lz -o lab1b-server lab1b-server.c

client:
	gcc -Wall -Wextra -lz -o lab1b-client lab1b-client.c

dist:
	tar -cvzf lab1b-505146702.tar.gz lab1b-server.c lab1b-client.c Makefile README

clean:
	rm -f lab1b-505146702.tar.gz lab1b-server lab1b-client
