# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

dist:
	tar -cvzf lab4a-505146702.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

clean:
	rm -f lab1b-505146702.tar.gz 
