# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

default:
	gcc -Wall -Wextra -g -o lab1a lab1a.c
clean:
	rm -f lab1a lab1a-505146702.tar.gz
dist:
	tar -czf lab1a-505146702.tar.gz lab1a.c Makefile README
