# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

default:
	chmod u+x lab3b.sh
	-ln lab3b.sh lab3b

clean:
	rm -f lab3b lab3b-505146702.tar.gz

dist:
	tar -czvf lab3b-505146702.tar.gz lab3b.py Makefile README lab3b.sh




