# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c -lm

clean:
	rm -f lab3a lab3a-505146702.tar.gz

dist:
	tar -czvf lab3a-505146702.tar.gz lab3a.c ext2_fs.h Makefile README




