# NAME: Sum Yi Li
# EMAIL: sammyli0106@gmail.com
# ID: 505146702

default:
	gcc -lmraa -lm -Wall -Wextra -g -o lab4c_tcp lab4c_tcp.c
	gcc -lmraa -lm -lssl -lcrypto -Wall -Wextra -g -o lab4c_tls lab4c_tls.c

clean:
	rm -f lab4c_tls lab4c_tcp lab4c-505146702.tar.gz

dist:
	tar -czvf lab4c-505146702.tar.gz lab4c_tls.c lab4c_tcp.c Makefile README




